#!/usr/bin/env bash

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

BASE_DIR="$(dirname "$SCRIPT_DIR")"

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Find the specified suspect node from all log files

SYNOPSIS
   ./$EXECUTABLE [suspect_node] [-?]

DESRIPTION
   Finds the specified suspect node from all log files

OPTIONS
   suspect_node
             Optional suspect node. If unspecified, then assigns all nodes as suspects.

EOF
exit
fi

SUSPECT_NODES="$1"

if [ "$SUSPECT_NODES" = "" ]; then
   SUSPECT_NODES="$ALL_NODES"
fi

TIMESTAMP=`date +%y%m%d-%H%M%S`
TMP_FILE_FIRST="/tmp/padogrid-first-$EXECUTABLE-$TIMESTAMP.log"
TMP_FILE="/tmp/padogrid-$EXECUTABLE-$TIMESTAMP.log"
TMP_FILE2="/tmp/padogrid-1-$EXECUTABLE-$TIMESTAMP.log"
if [ -f $TMP_FILE ]; then
   rm $TMP_FILE
fi
if [ -f $TMP_FILE2 ]; then
   rm $TMP_FILE2
fi

echo ""
for SUSPECT_NODE in $SUSPECT_NODES; do
   for NODE in $ALL_NODES; do
      if [ "$NODE" != "$SUSPECT_NODE" ]; then
         ./show_suspect_node_pair -first $SUSPECT_NODE $NODE >> $TMP_FILE_FIRST
         ./show_suspect_node_pair $SUSPECT_NODE $NODE >> $TMP_FILE
      fi
   done

   echo "Suspect: $SUSPECT_NODE"
   echo "---------------------------------------"
   if [ ! -s $TMP_FILE ]; then
      echo "Not found."
   else
     echo "For:"
     while IFS= read -r line; do
        echo "$line" | sed -e 's/^.*for //' -e 's/).*$/)/' >> $TMP_FILE2
     done < "$TMP_FILE"
     unset IFS
     if [ -f "$TMP_FILE2" ]; then
        cat $TMP_FILE2 | awk '!a[$0]++' | sort
     fi
     echo ""
     echo "First logged:"
     sort $TMP_FILE_FIRST | awk '!a[$0]++'
     echo ""
     echo "Last logged:"
     sort $TMP_FILE | awk '!a[$0]++'
     rm $TMP_FILE
   fi
   echo ""
done
echo "Now: $(date '+%Y/%m/%d-%H:%M:%S %Z')"
