#!/usr/bin/env bash

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

BASE_DIR="$(dirname "$SCRIPT_DIR")"

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Display missing disk stores

SYNOPSIS
   ./$EXECUTABLE [-?]

DESRIPTION
   Displays missing disk stores.

DEFAULT:
   ./$EXECUTABLE

EOF
exit
fi


FILTER1="stale data"
FILTER2="missing-disk-store"

TIMESTAMP=`date +%y%m%d-%H%M%S`
TMP_FILE="/tmp/padogrid-$EXECUTABLE-$TIMESTAMP.log"
if [ -f $TMP_FILE ]; then
   rm $TMP_FILE
fi
pushd $APP_LOG_DIR > /dev/null 2>&1
grep . $LOCATOR_FILES | sed -n -e "/$FILTER1/,/$FILTER2/p" | sed -e '/\[$/d' -e '/\]$/d' -e '/My persistent id/d' > $TMP_FILE
grep . $SERVER_FILES | sed -n -e "/$FILTER1/,/$FILTER2/p" >> $TMP_FILE

echo ""
echo "Missing Disk Stores"
echo "-------------------"
line_count=0
log_file=""
while IFS= read -r line; do
   prev_log_file="$log_file"
   let line_count=line_count+1
   log_file=$(echo $line | sed 's/:.*$//')
   if [ "$log_file" != "$prev_log_file" ]; then
      echo "$log_file"
   fi
   if [[ "$line" == *"$FILTER1"* ]]; then
      timestamp=$(echo $line | sed -e "s/$log_file://" -e 's/^.*info //' -e "s/$CLUSTER-.*$//"  -e 's/info.*//i')
      region=$(echo $line | sed -e 's/^.*Region //' -e 's/has potentially stale data.*$//')
      echo "$TTee $timestamp"
   else
      case $line_count in
      2)
         diskstore_id=$(echo $line | sed 's/.*DiskStore ID: //')
         ;;
      3)
         name=$(echo $line | sed 's/.*Name: //')
         echo "$TBar   $TTee $name"
         if [ "$region" != "" ]; then
            echo "$TBar   $TBar   $TTee $region"
         fi
         echo "$TBar   $TBar   $TTee $diskstore_id"
         ;;
      4)
         location=$(echo $line | sed 's/.*Location: //')
         address=$(echo $location -e 's/:.*$//' -e 's/\///g')
         echo "$TBar   $TBar   $TLel $address"
         ;;
      *)
         if [ $line_count -gt 5 ]; then
            offline_disk_store_id=$(echo $line | grep 'DiskStore ID:' | sed 's/.*DiskStore ID: //')
            name=$(echo $line | grep 'Name:' | sed 's/.*Name: //')
            offline_location=$(echo $line | grep 'Location:' | sed 's/.*Location: //')
            offline_address=$(echo $offline_location | sed -e 's/:.*$//' -e 's/\///g')
            end_line=$(echo $line | grep "$FILTER2")
            if [ "$end_line" != "" ]; then
               line_count=0
            elif [ "$offline_disk_store_id" != "" ]; then
               echo -e "$TBar   $TTee ${CError}offline${CNone}"
               echo "$TBar   $TBar   $TTee $offline_disk_store_id"
            elif [ "$name" != "" ]; then
               echo "$TBar   $TBar   $TTee $name"
            elif [ "$offline_address" != "" ]; then
               echo "$TBar   $TBar   $TTee $offline_address"
            fi
         fi
         ;;
      esac
   fi
done < "$TMP_FILE"
unset IFS
rm $TMP_FILE
popd > /dev/null 2>&1

echo "Now: $(date '+%Y/%m/%d-%H:%M:%S %Z')"
echo ""
