#!/usr/bin/env bash

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

BASE_DIR="$(dirname "$SCRIPT_DIR")"

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Display unexpectedly left members in chronological order

SYNOPSIS
   ./$EXECUTABLE [suspect_node] [-?]

DESRIPTION
   Displays unexpectedly left members in chronological order.

EOF
exit
fi

LOCATOR_FILES="*locator*.log"

TIMESTAMP=`date +%y%m%d-%H%M%S`
TMP_FILE="/tmp/padogrid-$EXECUTABLE-$TIMESTAMP.log"
if [ -f $TMP_FILE ]; then
   rm $TMP_FILE
fi
pushd $APP_LOG_DIR > /dev/null 2>&1
grep "unexpectedly left" *.log > $TMP_FILE
echo ""
echo "Member unexpectedly left:"
echo "-------------------------"
prev_log_file=""
while IFS= read -r line; do
  log_file=$(echo $line | sed 's/:.*$//')
  timestamp=$(echo $line | sed -e "s/$log_file://" -e 's/^.*info //' -e 's/UTC.*$/UTC/' -e 's/ INFO.*$//')
  member=$(echo $line | sed -e 's/^.*Member at//' -e 's/ unexpectedly.*$//')
  if [ "$prev_log_file" != "$log_file" ]; then
     echo "$log_file"
     prev_log_file=$log_file
  fi
  echo "$TTee $timestamp"
  echo -e "$TBar   $TLel ${CError}$member${CNone}"
done < "$TMP_FILE"
unset IFS
rm $TMP_FILE
popd > /dev/null 2>&1

echo ""
