#!/usr/bin/env bash

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

BASE_DIR="$(dirname "$SCRIPT_DIR")"

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Start cluster with node-01 as the lead

SYNOPSIS
   ./$EXECUTABLE [-?]

DESRIPTION
   Starts cluster with node-01 as the lead. This is done by starting the locators individually
   and then the node-01 member in the foreground. Once node-01 is up, then the remaining nodes
    are started.

EOF
exit
fi

start_locator -num 1
start_locator -num 2
start_member -fg -num 1

for i in $(seq 2 5); do
   start_member -num $i
done
